use SAV_UNIVER;

select avg(AUDITORIUM.AUDITORIUM_CAPACITY)[AVG],
    max(AUDITORIUM.AUDITORIUM_CAPACITY)[MAX],
    min(AUDITORIUM.AUDITORIUM_CAPACITY)[MIN],
    sum(AUDITORIUM.AUDITORIUM_CAPACITY)[SUM],
	count(*)[COUNT]
from AUDITORIUM;

select AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
	avg(AUDITORIUM.AUDITORIUM_CAPACITY)[AVG],
    max(AUDITORIUM.AUDITORIUM_CAPACITY)[MAX],
    min(AUDITORIUM.AUDITORIUM_CAPACITY)[MIN],
    sum(AUDITORIUM.AUDITORIUM_CAPACITY)[SUM],
	count(*)[COUNT]
from AUDITORIUM_TYPE
join AUDITORIUM on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
group by AUDITORIUM_TYPE.AUDITORIUM_TYPENAME;

select * from PROGRESS;

select *
from (
select 
case 
when NOTE = 10 then '10'
when NOTE between 8 and 9  then '8-9'
when NOTE between 6 and 7  then '6-7'
else '4-5'
end[NOTE]
,
count (*)[COUNT]
from PROGRESS
group by
case 
when NOTE = 10 then '10'
when NOTE between 8 and 9  then '8-9'
when NOTE between 6 and 7  then '6-7'
else '4-5'
end
) as T
order by case
when NOTE = '10' then 1
when NOTE = '8-9'  then 2
when NOTE = '6-7'  then 3
else 4
end

select PROFESSION.FACULTY[ФАКУЛЬТЕТ], PROFESSION.PROFESSION[СПЕЦИАЛЬНОСТЬ], GROUPS.COURSE[КУРС], round(avg(cast(PROGRESS.NOTE as float(4))),2)[ОЦЕНКА] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by
PROFESSION.PROFESSION,
GROUPS.COURSE,
PROFESSION.FACULTY;


select PROFESSION.FACULTY[ФАКУЛЬТЕТ], PROFESSION.PROFESSION[СПЕЦИАЛЬНОСТЬ], GROUPS.COURSE[КУРС], round(avg(cast(PROGRESS.NOTE as float(4))),2)[ОЦЕНКА] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.SUBJECT = 'БД' or PROGRESS.SUBJECT = 'ОАиП'
group by
PROFESSION.PROFESSION,
GROUPS.COURSE,
PROFESSION.FACULTY

select PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИТ'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT


select PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИТ'
group by rollup(
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT)

select PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
group by rollup(
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT)

select FACULTY.FACULTY,PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
group by rollup(
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT)

select FACULTY.FACULTY,PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
group by cube(
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT)

select FACULTY.FACULTY[Факультет],PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИДиП'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT
union 
select FACULTY.FACULTY[Факультет],PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИТ'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT

select FACULTY.FACULTY[Факультет],PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИДиП'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT
INTERSECT
select FACULTY.FACULTY[Факультет],PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИТ'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT

select FACULTY.FACULTY[Факультет],PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИДиП'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT
EXCEPT
select FACULTY.FACULTY[Факультет],PROFESSION.PROFESSION_NAME[Специальность], PROGRESS.SUBJECT[Дисциплина], round(avg(cast(PROGRESS.NOTE as float(4))),1)[Оценка] from PROFESSION
join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
join FACULTY on FACULTY.FACULTY = PROFESSION.FACULTY
where FACULTY.FACULTY = 'ИТ'
group by
FACULTY.FACULTY,
PROFESSION.PROFESSION_NAME,
PROGRESS.SUBJECT

select PROGRESS.SUBJECT[Дисциплина],PROGRESS.NOTE[Оценка], count(*)[Число студентов] from PROGRESS
group by
PROGRESS.SUBJECT,
PROGRESS.NOTE
having PROGRESS.NOTE between 8 and 9
order by
PROGRESS.SUBJECT,
PROGRESS.NOTE
