use SAV_UNIVER;


select PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME, PULPIT.FACULTY from PULPIT join PROFESSION
on PULPIT.FACULTY in (select PROFESSION.FACULTY from PROFESSION where ((PROFESSION_NAME like '%технология%') or (PROFESSION_NAME like '%технологии%'))); 

