
use SAV_UNIVER;

select PULPIT.PULPIT_NAME,
isnull(TEACHER.TEACHER_NAME,'***')
from PULPIT
left join TEACHER
on TEACHER.PULPIT = PULPIT.PULPIT
where TEACHER.PULPIT is NULL;
;


select TEACHER.TEACHER_NAME,
isnull(TEACHER.TEACHER_NAME,'***')
from PULPIT
right join TEACHER
on TEACHER.PULPIT = PULPIT.PULPIT
where PULPIT.PULPIT is NULL;
;

select PULPIT.PULPIT_NAME,
isnull(TEACHER.TEACHER_NAME,'***')
from TEACHER
full join PULPIT
on TEACHER.PULPIT = PULPIT.PULPIT
where TEACHER.PULPIT is not NULL and PULPIT.PULPIT is not NULL
;


/*
select PULPIT.PULPIT_NAME, TEACHER.TEACHER_NAME
from TEACHER left join PULPIT
on TEACHER.PULPIT = PULPIT.PULPIT

select PULPIT.PULPIT_NAME, TEACHER.TEACHER_NAME
from TEACHER full join PULPIT
on TEACHER.PULPIT = PULPIT.PULPIT
;
*/

/*
select isnull(TEACHER.TEACHER_NAME,'***')[TEACHER_NAME]
from TEACHER full join PULPIT
on TEACHER.PULPIT = PULPIT.PULPIT

select isnull(PULPIT.PULPIT_NAME,'***')[PULPIT_NAME]
from TEACHER full join PULPIT
on TEACHER.PULPIT = PULPIT.PULPIT

select isnull(PULPIT.PULPIT_NAME,'***')[PULPIT_NAME], isnull(TEACHER.TEACHER_NAME,'***')[TEACHER_NAME]
from TEACHER full join PULPIT
on TEACHER.PULPIT = PULPIT.PULPIT
*/

